// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: achievement.sql

package sqldb

import (
	"context"
	"time"
)

const archiveAchievement = `-- name: ArchiveAchievement :exec
UPDATE achievements SET archived_at = datetime('now') WHERE id = ? AND archived_at IS NULL
`

func (q *Queries) ArchiveAchievement(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, archiveAchievement, id)
	return err
}

const createAchievement = `-- name: CreateAchievement :one
INSERT INTO achievements (slug, name, description, title, combinator, bonus_points)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, slug, name, description, title, combinator, bonus_points, archived_at, created_at
`

type CreateAchievementParams struct {
	Slug        string
	Name        string
	Description *string
	Title       *string
	Combinator  string
	BonusPoints int64
}

func (q *Queries) CreateAchievement(ctx context.Context, arg CreateAchievementParams) (Achievement, error) {
	row := q.db.QueryRowContext(ctx, createAchievement,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Title,
		arg.Combinator,
		arg.BonusPoints,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Title,
		&i.Combinator,
		&i.BonusPoints,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAchievementRules = `-- name: DeleteAchievementRules :exec
DELETE FROM achievement_rules WHERE achievement_id = ?
`

func (q *Queries) DeleteAchievementRules(ctx context.Context, achievementID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAchievementRules, achievementID)
	return err
}

const getAchievement = `-- name: GetAchievement :one
SELECT id, slug, name, description, title, combinator, bonus_points, archived_at, created_at FROM achievements WHERE id = ?
`

func (q *Queries) GetAchievement(ctx context.Context, id int64) (Achievement, error) {
	row := q.db.QueryRowContext(ctx, getAchievement, id)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Title,
		&i.Combinator,
		&i.BonusPoints,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAchievementBySlug = `-- name: GetAchievementBySlug :one
SELECT id, slug, name, description, title, combinator, bonus_points, archived_at, created_at FROM achievements WHERE slug = ? AND archived_at IS NULL
`

func (q *Queries) GetAchievementBySlug(ctx context.Context, slug string) (Achievement, error) {
	row := q.db.QueryRowContext(ctx, getAchievementBySlug, slug)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Title,
		&i.Combinator,
		&i.BonusPoints,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAchievementRule = `-- name: InsertAchievementRule :one
INSERT INTO achievement_rules (achievement_id, category_id, metric, threshold)
VALUES (?, ?, ?, ?)
RETURNING id, achievement_id, category_id, metric, threshold
`

type InsertAchievementRuleParams struct {
	AchievementID int64
	CategoryID    *int64
	Metric        string
	Threshold     int64
}

func (q *Queries) InsertAchievementRule(ctx context.Context, arg InsertAchievementRuleParams) (AchievementRule, error) {
	row := q.db.QueryRowContext(ctx, insertAchievementRule,
		arg.AchievementID,
		arg.CategoryID,
		arg.Metric,
		arg.Threshold,
	)
	var i AchievementRule
	err := row.Scan(
		&i.ID,
		&i.AchievementID,
		&i.CategoryID,
		&i.Metric,
		&i.Threshold,
	)
	return i, err
}

const listAchievementRules = `-- name: ListAchievementRules :many
SELECT id, achievement_id, category_id, metric, threshold FROM achievement_rules WHERE achievement_id = ? ORDER BY id
`

func (q *Queries) ListAchievementRules(ctx context.Context, achievementID int64) ([]AchievementRule, error) {
	rows, err := q.db.QueryContext(ctx, listAchievementRules, achievementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AchievementRule{}
	for rows.Next() {
		var i AchievementRule
		if err := rows.Scan(
			&i.ID,
			&i.AchievementID,
			&i.CategoryID,
			&i.Metric,
			&i.Threshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAchievements = `-- name: ListAchievements :many
SELECT id, slug, name, description, title, combinator, bonus_points, archived_at, created_at FROM achievements WHERE archived_at IS NULL ORDER BY name
`

func (q *Queries) ListAchievements(ctx context.Context) ([]Achievement, error) {
	rows, err := q.db.QueryContext(ctx, listAchievements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Achievement{}
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Title,
			&i.Combinator,
			&i.BonusPoints,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEarnedAchievementsForKid = `-- name: ListEarnedAchievementsForKid :many
SELECT
    ka.kid_id, ka.achievement_id, ka.earned_at, ka.unseen,
    a.slug, a.name, a.description, a.title, a.combinator,
    a.bonus_points, a.archived_at, a.created_at
FROM kid_achievements ka
JOIN achievements a ON a.id = ka.achievement_id
WHERE ka.kid_id = ?
ORDER BY ka.earned_at DESC
`

type ListEarnedAchievementsForKidRow struct {
	KidID         int64
	AchievementID int64
	EarnedAt      time.Time
	Unseen        int64
	Slug          string
	Name          string
	Description   *string
	Title         *string
	Combinator    string
	BonusPoints   int64
	ArchivedAt    *time.Time
	CreatedAt     time.Time
}

func (q *Queries) ListEarnedAchievementsForKid(ctx context.Context, kidID int64) ([]ListEarnedAchievementsForKidRow, error) {
	rows, err := q.db.QueryContext(ctx, listEarnedAchievementsForKid, kidID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEarnedAchievementsForKidRow{}
	for rows.Next() {
		var i ListEarnedAchievementsForKidRow
		if err := rows.Scan(
			&i.KidID,
			&i.AchievementID,
			&i.EarnedAt,
			&i.Unseen,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Title,
			&i.Combinator,
			&i.BonusPoints,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnearnedAchievementRulesForKid = `-- name: ListUnearnedAchievementRulesForKid :many
SELECT
    a.id              AS achievement_id,
    a.slug            AS achievement_slug,
    a.name            AS achievement_name,
    a.description     AS achievement_description,
    a.title           AS achievement_title,
    a.combinator      AS achievement_combinator,
    a.bonus_points    AS achievement_bonus_points,
    a.archived_at     AS achievement_archived_at,
    a.created_at      AS achievement_created_at,
    r.id              AS rule_id,
    r.category_id     AS rule_category_id,
    r.metric          AS rule_metric,
    r.threshold       AS rule_threshold
FROM achievements a
INNER JOIN achievement_rules r ON r.achievement_id = a.id
WHERE a.archived_at IS NULL
  AND a.id NOT IN (
      SELECT achievement_id FROM kid_achievements WHERE kid_id = ?
  )
ORDER BY a.id, r.id
`

type ListUnearnedAchievementRulesForKidRow struct {
	AchievementID          int64
	AchievementSlug        string
	AchievementName        string
	AchievementDescription *string
	AchievementTitle       *string
	AchievementCombinator  string
	AchievementBonusPoints int64
	AchievementArchivedAt  *time.Time
	AchievementCreatedAt   time.Time
	RuleID                 int64
	RuleCategoryID         *int64
	RuleMetric             string
	RuleThreshold          int64
}

// Engine entry point: list every active achievement the kid has not yet earned,
// joined to its rules so the engine can evaluate in a single round-trip.
// Returns one row per rule; rule-less achievements are filtered out by the INNER JOIN.
func (q *Queries) ListUnearnedAchievementRulesForKid(ctx context.Context, kidID int64) ([]ListUnearnedAchievementRulesForKidRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnearnedAchievementRulesForKid, kidID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnearnedAchievementRulesForKidRow{}
	for rows.Next() {
		var i ListUnearnedAchievementRulesForKidRow
		if err := rows.Scan(
			&i.AchievementID,
			&i.AchievementSlug,
			&i.AchievementName,
			&i.AchievementDescription,
			&i.AchievementTitle,
			&i.AchievementCombinator,
			&i.AchievementBonusPoints,
			&i.AchievementArchivedAt,
			&i.AchievementCreatedAt,
			&i.RuleID,
			&i.RuleCategoryID,
			&i.RuleMetric,
			&i.RuleThreshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAchievementEarned = `-- name: MarkAchievementEarned :exec
INSERT INTO kid_achievements (kid_id, achievement_id, unseen)
VALUES (?, ?, 1)
ON CONFLICT(kid_id, achievement_id) DO NOTHING
`

type MarkAchievementEarnedParams struct {
	KidID         int64
	AchievementID int64
}

func (q *Queries) MarkAchievementEarned(ctx context.Context, arg MarkAchievementEarnedParams) error {
	_, err := q.db.ExecContext(ctx, markAchievementEarned, arg.KidID, arg.AchievementID)
	return err
}

const markAchievementSeen = `-- name: MarkAchievementSeen :exec
UPDATE kid_achievements SET unseen = 0
WHERE kid_id = ? AND achievement_id = ?
`

type MarkAchievementSeenParams struct {
	KidID         int64
	AchievementID int64
}

func (q *Queries) MarkAchievementSeen(ctx context.Context, arg MarkAchievementSeenParams) error {
	_, err := q.db.ExecContext(ctx, markAchievementSeen, arg.KidID, arg.AchievementID)
	return err
}

const sumEarnedAchievementBonusesForKid = `-- name: SumEarnedAchievementBonusesForKid :one
SELECT CAST(COALESCE(SUM(a.bonus_points), 0) AS INTEGER) AS total
FROM kid_achievements ka
JOIN achievements a ON a.id = ka.achievement_id
WHERE ka.kid_id = ?
`

// Balance support: sum of bonus_points across achievements the kid has earned.
func (q *Queries) SumEarnedAchievementBonusesForKid(ctx context.Context, kidID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumEarnedAchievementBonusesForKid, kidID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const unarchiveAchievement = `-- name: UnarchiveAchievement :exec
UPDATE achievements SET archived_at = NULL WHERE id = ?
`

func (q *Queries) UnarchiveAchievement(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unarchiveAchievement, id)
	return err
}

const updateAchievement = `-- name: UpdateAchievement :exec
UPDATE achievements
SET name = ?, description = ?, title = ?, combinator = ?, bonus_points = ?
WHERE id = ?
`

type UpdateAchievementParams struct {
	Name        string
	Description *string
	Title       *string
	Combinator  string
	BonusPoints int64
	ID          int64
}

func (q *Queries) UpdateAchievement(ctx context.Context, arg UpdateAchievementParams) error {
	_, err := q.db.ExecContext(ctx, updateAchievement,
		arg.Name,
		arg.Description,
		arg.Title,
		arg.Combinator,
		arg.BonusPoints,
		arg.ID,
	)
	return err
}

const upsertAchievementBySlug = `-- name: UpsertAchievementBySlug :one
INSERT INTO achievements (slug, name, description, title, combinator, bonus_points)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(slug) WHERE archived_at IS NULL
DO UPDATE SET
    name = excluded.name,
    description = excluded.description,
    title = excluded.title,
    combinator = excluded.combinator,
    bonus_points = excluded.bonus_points
RETURNING id, slug, name, description, title, combinator, bonus_points, archived_at, created_at
`

type UpsertAchievementBySlugParams struct {
	Slug        string
	Name        string
	Description *string
	Title       *string
	Combinator  string
	BonusPoints int64
}

func (q *Queries) UpsertAchievementBySlug(ctx context.Context, arg UpsertAchievementBySlugParams) (Achievement, error) {
	row := q.db.QueryRowContext(ctx, upsertAchievementBySlug,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Title,
		arg.Combinator,
		arg.BonusPoints,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Title,
		&i.Combinator,
		&i.BonusPoints,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}
