// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package sqldb

import (
	"context"
	"time"
)

const countActivitiesForKid = `-- name: CountActivitiesForKid :one
SELECT COUNT(*) AS total
FROM activities a
JOIN activity_types t ON t.id = a.activity_type_id
WHERE a.kid_id = ?
  AND a.voided_at IS NULL
  AND (?2 IS NULL OR t.category_id = ?2)
`

type CountActivitiesForKidParams struct {
	KidID      int64
	CategoryID interface{}
}

// Engine support: count activities for a kid, optionally filtered by category.
// Caller passes a non-NULL category_id to scope; NULL aggregates across all categories.
func (q *Queries) CountActivitiesForKid(ctx context.Context, arg CountActivitiesForKidParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivitiesForKid, arg.KidID, arg.CategoryID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getActivity = `-- name: GetActivity :one
SELECT id, kid_id, activity_type_id, quantity, xp_awarded, points_awarded, note, occurred_at, created_at, voided_at, void_reason FROM activities WHERE id = ?
`

func (q *Queries) GetActivity(ctx context.Context, id int64) (Activity, error) {
	row := q.db.QueryRowContext(ctx, getActivity, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.KidID,
		&i.ActivityTypeID,
		&i.Quantity,
		&i.XpAwarded,
		&i.PointsAwarded,
		&i.Note,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.VoidedAt,
		&i.VoidReason,
	)
	return i, err
}

const insertActivity = `-- name: InsertActivity :one
INSERT INTO activities (
    kid_id, activity_type_id, quantity, xp_awarded, points_awarded, note, occurred_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, kid_id, activity_type_id, quantity, xp_awarded, points_awarded, note, occurred_at, created_at, voided_at, void_reason
`

type InsertActivityParams struct {
	KidID          int64
	ActivityTypeID int64
	Quantity       int64
	XpAwarded      int64
	PointsAwarded  int64
	Note           *string
	OccurredAt     time.Time
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, insertActivity,
		arg.KidID,
		arg.ActivityTypeID,
		arg.Quantity,
		arg.XpAwarded,
		arg.PointsAwarded,
		arg.Note,
		arg.OccurredAt,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.KidID,
		&i.ActivityTypeID,
		&i.Quantity,
		&i.XpAwarded,
		&i.PointsAwarded,
		&i.Note,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.VoidedAt,
		&i.VoidReason,
	)
	return i, err
}

const listActivitiesForKidSince = `-- name: ListActivitiesForKidSince :many
SELECT id, kid_id, activity_type_id, quantity, xp_awarded, points_awarded, note, occurred_at, created_at, voided_at, void_reason FROM activities
WHERE kid_id = ?
  AND voided_at IS NULL
  AND occurred_at >= ?
ORDER BY occurred_at DESC, id DESC
`

type ListActivitiesForKidSinceParams struct {
	KidID      int64
	OccurredAt time.Time
}

func (q *Queries) ListActivitiesForKidSince(ctx context.Context, arg ListActivitiesForKidSinceParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesForKidSince, arg.KidID, arg.OccurredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.KidID,
			&i.ActivityTypeID,
			&i.Quantity,
			&i.XpAwarded,
			&i.PointsAwarded,
			&i.Note,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.VoidedAt,
			&i.VoidReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivitiesForKid = `-- name: ListRecentActivitiesForKid :many
SELECT id, kid_id, activity_type_id, quantity, xp_awarded, points_awarded, note, occurred_at, created_at, voided_at, void_reason FROM activities
WHERE kid_id = ? AND voided_at IS NULL
ORDER BY occurred_at DESC, id DESC
LIMIT ?
`

type ListRecentActivitiesForKidParams struct {
	KidID int64
	Limit int64
}

func (q *Queries) ListRecentActivitiesForKid(ctx context.Context, arg ListRecentActivitiesForKidParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listRecentActivitiesForKid, arg.KidID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.KidID,
			&i.ActivityTypeID,
			&i.Quantity,
			&i.XpAwarded,
			&i.PointsAwarded,
			&i.Note,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.VoidedAt,
			&i.VoidReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumActivityPointsForKid = `-- name: SumActivityPointsForKid :one
SELECT CAST(COALESCE(SUM(a.points_awarded), 0) AS INTEGER) AS total
FROM activities a
JOIN activity_types t ON t.id = a.activity_type_id
WHERE a.kid_id = ?
  AND a.voided_at IS NULL
  AND (?2 IS NULL OR t.category_id = ?2)
`

type SumActivityPointsForKidParams struct {
	KidID      int64
	CategoryID interface{}
}

// Engine + Balance support: sum points awarded from activities for a kid,
// optionally scoped to a category. Category-scoped points rules use this directly.
func (q *Queries) SumActivityPointsForKid(ctx context.Context, arg SumActivityPointsForKidParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumActivityPointsForKid, arg.KidID, arg.CategoryID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumActivityXPForKid = `-- name: SumActivityXPForKid :one
SELECT CAST(COALESCE(SUM(a.xp_awarded), 0) AS INTEGER) AS total
FROM activities a
JOIN activity_types t ON t.id = a.activity_type_id
WHERE a.kid_id = ?
  AND a.voided_at IS NULL
  AND (?2 IS NULL OR t.category_id = ?2)
`

type SumActivityXPForKidParams struct {
	KidID      int64
	CategoryID interface{}
}

// Engine support: sum xp_awarded, optionally scoped to a category.
func (q *Queries) SumActivityXPForKid(ctx context.Context, arg SumActivityXPForKidParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumActivityXPForKid, arg.KidID, arg.CategoryID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const voidActivity = `-- name: VoidActivity :exec
UPDATE activities
SET voided_at = datetime('now'), void_reason = ?
WHERE id = ? AND voided_at IS NULL
`

type VoidActivityParams struct {
	VoidReason *string
	ID         int64
}

func (q *Queries) VoidActivity(ctx context.Context, arg VoidActivityParams) error {
	_, err := q.db.ExecContext(ctx, voidActivity, arg.VoidReason, arg.ID)
	return err
}
