// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_type.sql

package sqldb

import (
	"context"
)

const archiveActivityType = `-- name: ArchiveActivityType :exec
UPDATE activity_types SET archived_at = datetime('now') WHERE id = ? AND archived_at IS NULL
`

func (q *Queries) ArchiveActivityType(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, archiveActivityType, id)
	return err
}

const createActivityType = `-- name: CreateActivityType :one
INSERT INTO activity_types (category_id, slug, name, description, xp_per_unit, points_per_unit)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, category_id, slug, name, description, xp_per_unit, points_per_unit, archived_at, created_at
`

type CreateActivityTypeParams struct {
	CategoryID    int64
	Slug          string
	Name          string
	Description   *string
	XpPerUnit     int64
	PointsPerUnit int64
}

func (q *Queries) CreateActivityType(ctx context.Context, arg CreateActivityTypeParams) (ActivityType, error) {
	row := q.db.QueryRowContext(ctx, createActivityType,
		arg.CategoryID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.XpPerUnit,
		arg.PointsPerUnit,
	)
	var i ActivityType
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.XpPerUnit,
		&i.PointsPerUnit,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActivityType = `-- name: GetActivityType :one
SELECT id, category_id, slug, name, description, xp_per_unit, points_per_unit, archived_at, created_at FROM activity_types WHERE id = ?
`

func (q *Queries) GetActivityType(ctx context.Context, id int64) (ActivityType, error) {
	row := q.db.QueryRowContext(ctx, getActivityType, id)
	var i ActivityType
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.XpPerUnit,
		&i.PointsPerUnit,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActivityTypeBySlug = `-- name: GetActivityTypeBySlug :one
SELECT id, category_id, slug, name, description, xp_per_unit, points_per_unit, archived_at, created_at FROM activity_types WHERE slug = ? AND archived_at IS NULL
`

func (q *Queries) GetActivityTypeBySlug(ctx context.Context, slug string) (ActivityType, error) {
	row := q.db.QueryRowContext(ctx, getActivityTypeBySlug, slug)
	var i ActivityType
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.XpPerUnit,
		&i.PointsPerUnit,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityTypes = `-- name: ListActivityTypes :many
SELECT id, category_id, slug, name, description, xp_per_unit, points_per_unit, archived_at, created_at FROM activity_types
WHERE archived_at IS NULL
ORDER BY category_id, name
`

func (q *Queries) ListActivityTypes(ctx context.Context) ([]ActivityType, error) {
	rows, err := q.db.QueryContext(ctx, listActivityTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityType{}
	for rows.Next() {
		var i ActivityType
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.XpPerUnit,
			&i.PointsPerUnit,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityTypesByCategory = `-- name: ListActivityTypesByCategory :many
SELECT id, category_id, slug, name, description, xp_per_unit, points_per_unit, archived_at, created_at FROM activity_types
WHERE category_id = ? AND archived_at IS NULL
ORDER BY name
`

func (q *Queries) ListActivityTypesByCategory(ctx context.Context, categoryID int64) ([]ActivityType, error) {
	rows, err := q.db.QueryContext(ctx, listActivityTypesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityType{}
	for rows.Next() {
		var i ActivityType
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.XpPerUnit,
			&i.PointsPerUnit,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveActivityType = `-- name: UnarchiveActivityType :exec
UPDATE activity_types SET archived_at = NULL WHERE id = ?
`

func (q *Queries) UnarchiveActivityType(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unarchiveActivityType, id)
	return err
}

const updateActivityType = `-- name: UpdateActivityType :exec
UPDATE activity_types
SET category_id = ?, name = ?, description = ?, xp_per_unit = ?, points_per_unit = ?
WHERE id = ?
`

type UpdateActivityTypeParams struct {
	CategoryID    int64
	Name          string
	Description   *string
	XpPerUnit     int64
	PointsPerUnit int64
	ID            int64
}

func (q *Queries) UpdateActivityType(ctx context.Context, arg UpdateActivityTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateActivityType,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.XpPerUnit,
		arg.PointsPerUnit,
		arg.ID,
	)
	return err
}

const upsertActivityTypeBySlug = `-- name: UpsertActivityTypeBySlug :one
INSERT INTO activity_types (category_id, slug, name, description, xp_per_unit, points_per_unit)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(slug) WHERE archived_at IS NULL
DO UPDATE SET
    category_id = excluded.category_id,
    name = excluded.name,
    description = excluded.description,
    xp_per_unit = excluded.xp_per_unit,
    points_per_unit = excluded.points_per_unit
RETURNING id, category_id, slug, name, description, xp_per_unit, points_per_unit, archived_at, created_at
`

type UpsertActivityTypeBySlugParams struct {
	CategoryID    int64
	Slug          string
	Name          string
	Description   *string
	XpPerUnit     int64
	PointsPerUnit int64
}

func (q *Queries) UpsertActivityTypeBySlug(ctx context.Context, arg UpsertActivityTypeBySlugParams) (ActivityType, error) {
	row := q.db.QueryRowContext(ctx, upsertActivityTypeBySlug,
		arg.CategoryID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.XpPerUnit,
		arg.PointsPerUnit,
	)
	var i ActivityType
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.XpPerUnit,
		&i.PointsPerUnit,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}
