// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package sqldb

import (
	"context"
)

const archiveCategory = `-- name: ArchiveCategory :exec
UPDATE categories SET archived_at = datetime('now') WHERE id = ? AND archived_at IS NULL
`

func (q *Queries) ArchiveCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, archiveCategory, id)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (slug, name, description, icon, color)
VALUES (?, ?, ?, ?, ?)
RETURNING id, slug, name, description, icon, color, archived_at, created_at
`

type CreateCategoryParams struct {
	Slug        string
	Name        string
	Description *string
	Icon        *string
	Color       *string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, slug, name, description, icon, color, archived_at, created_at FROM categories WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, slug, name, description, icon, color, archived_at, created_at FROM categories WHERE slug = ? AND archived_at IS NULL
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, slug, name, description, icon, color, archived_at, created_at FROM categories
WHERE archived_at IS NULL
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Color,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveCategory = `-- name: UnarchiveCategory :exec
UPDATE categories SET archived_at = NULL WHERE id = ?
`

func (q *Queries) UnarchiveCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unarchiveCategory, id)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories
SET name = ?, description = ?, icon = ?, color = ?
WHERE id = ?
`

type UpdateCategoryParams struct {
	Name        string
	Description *string
	Icon        *string
	Color       *string
	ID          int64
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Color,
		arg.ID,
	)
	return err
}

const upsertCategoryBySlug = `-- name: UpsertCategoryBySlug :one
INSERT INTO categories (slug, name, description, icon, color)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(slug) WHERE archived_at IS NULL
DO UPDATE SET name = excluded.name, description = excluded.description,
              icon = excluded.icon, color = excluded.color
RETURNING id, slug, name, description, icon, color, archived_at, created_at
`

type UpsertCategoryBySlugParams struct {
	Slug        string
	Name        string
	Description *string
	Icon        *string
	Color       *string
}

func (q *Queries) UpsertCategoryBySlug(ctx context.Context, arg UpsertCategoryBySlugParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, upsertCategoryBySlug,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}
