// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kid.sql

package sqldb

import (
	"context"
)

const archiveKid = `-- name: ArchiveKid :exec
UPDATE kids SET archived_at = datetime('now') WHERE id = ? AND archived_at IS NULL
`

func (q *Queries) ArchiveKid(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, archiveKid, id)
	return err
}

const createKid = `-- name: CreateKid :one
INSERT INTO kids (name, avatar_slug, color, display_order)
VALUES (?, ?, ?, ?)
RETURNING id, name, avatar_slug, color, display_order, archived_at, created_at
`

type CreateKidParams struct {
	Name         string
	AvatarSlug   string
	Color        string
	DisplayOrder int64
}

func (q *Queries) CreateKid(ctx context.Context, arg CreateKidParams) (Kid, error) {
	row := q.db.QueryRowContext(ctx, createKid,
		arg.Name,
		arg.AvatarSlug,
		arg.Color,
		arg.DisplayOrder,
	)
	var i Kid
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AvatarSlug,
		&i.Color,
		&i.DisplayOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getKid = `-- name: GetKid :one
SELECT id, name, avatar_slug, color, display_order, archived_at, created_at FROM kids WHERE id = ?
`

func (q *Queries) GetKid(ctx context.Context, id int64) (Kid, error) {
	row := q.db.QueryRowContext(ctx, getKid, id)
	var i Kid
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AvatarSlug,
		&i.Color,
		&i.DisplayOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listKids = `-- name: ListKids :many
SELECT id, name, avatar_slug, color, display_order, archived_at, created_at FROM kids
WHERE (?1 IS NOT NULL AND ?1 = 1)
   OR archived_at IS NULL
ORDER BY display_order, name
`

func (q *Queries) ListKids(ctx context.Context, includeArchived interface{}) ([]Kid, error) {
	rows, err := q.db.QueryContext(ctx, listKids, includeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Kid{}
	for rows.Next() {
		var i Kid
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AvatarSlug,
			&i.Color,
			&i.DisplayOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveKid = `-- name: UnarchiveKid :exec
UPDATE kids SET archived_at = NULL WHERE id = ?
`

func (q *Queries) UnarchiveKid(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unarchiveKid, id)
	return err
}

const updateKid = `-- name: UpdateKid :exec
UPDATE kids
SET name = ?, avatar_slug = ?, color = ?, display_order = ?
WHERE id = ?
`

type UpdateKidParams struct {
	Name         string
	AvatarSlug   string
	Color        string
	DisplayOrder int64
	ID           int64
}

func (q *Queries) UpdateKid(ctx context.Context, arg UpdateKidParams) error {
	_, err := q.db.ExecContext(ctx, updateKid,
		arg.Name,
		arg.AvatarSlug,
		arg.Color,
		arg.DisplayOrder,
		arg.ID,
	)
	return err
}
