// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqldb

import (
	"time"
)

type Achievement struct {
	ID          int64
	Slug        string
	Name        string
	Description *string
	Title       *string
	Combinator  string
	BonusPoints int64
	ArchivedAt  *time.Time
	CreatedAt   time.Time
}

type AchievementRule struct {
	ID            int64
	AchievementID int64
	CategoryID    *int64
	Metric        string
	Threshold     int64
}

type Activity struct {
	ID             int64
	KidID          int64
	ActivityTypeID int64
	Quantity       int64
	XpAwarded      int64
	PointsAwarded  int64
	Note           *string
	OccurredAt     time.Time
	CreatedAt      time.Time
	VoidedAt       *time.Time
	VoidReason     *string
}

type ActivityType struct {
	ID            int64
	CategoryID    int64
	Slug          string
	Name          string
	Description   *string
	XpPerUnit     int64
	PointsPerUnit int64
	ArchivedAt    *time.Time
	CreatedAt     time.Time
}

type Category struct {
	ID          int64
	Slug        string
	Name        string
	Description *string
	Icon        *string
	Color       *string
	ArchivedAt  *time.Time
	CreatedAt   time.Time
}

type Kid struct {
	ID           int64
	Name         string
	AvatarSlug   string
	Color        string
	DisplayOrder int64
	ArchivedAt   *time.Time
	CreatedAt    time.Time
}

type KidAchievement struct {
	KidID         int64
	AchievementID int64
	EarnedAt      time.Time
	Unseen        int64
}

type PointAdjustment struct {
	ID          int64
	KidID       int64
	PointsDelta int64
	Reason      *string
	CreatedAt   time.Time
	VoidedAt    *time.Time
	VoidReason  *string
}

type Redemption struct {
	ID          int64
	KidID       int64
	RewardID    int64
	PointsSpent int64
	Status      string
	RequestedAt time.Time
	DecidedAt   *time.Time
}

type Reward struct {
	ID          int64
	Slug        string
	Name        string
	Description *string
	CostPoints  int64
	Active      int64
	ArchivedAt  *time.Time
	CreatedAt   time.Time
}
