// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: point_adjustment.sql

package sqldb

import (
	"context"
)

const getPointAdjustment = `-- name: GetPointAdjustment :one
SELECT id, kid_id, points_delta, reason, created_at, voided_at, void_reason FROM point_adjustments WHERE id = ?
`

func (q *Queries) GetPointAdjustment(ctx context.Context, id int64) (PointAdjustment, error) {
	row := q.db.QueryRowContext(ctx, getPointAdjustment, id)
	var i PointAdjustment
	err := row.Scan(
		&i.ID,
		&i.KidID,
		&i.PointsDelta,
		&i.Reason,
		&i.CreatedAt,
		&i.VoidedAt,
		&i.VoidReason,
	)
	return i, err
}

const insertPointAdjustment = `-- name: InsertPointAdjustment :one
INSERT INTO point_adjustments (kid_id, points_delta, reason)
VALUES (?, ?, ?)
RETURNING id, kid_id, points_delta, reason, created_at, voided_at, void_reason
`

type InsertPointAdjustmentParams struct {
	KidID       int64
	PointsDelta int64
	Reason      *string
}

func (q *Queries) InsertPointAdjustment(ctx context.Context, arg InsertPointAdjustmentParams) (PointAdjustment, error) {
	row := q.db.QueryRowContext(ctx, insertPointAdjustment, arg.KidID, arg.PointsDelta, arg.Reason)
	var i PointAdjustment
	err := row.Scan(
		&i.ID,
		&i.KidID,
		&i.PointsDelta,
		&i.Reason,
		&i.CreatedAt,
		&i.VoidedAt,
		&i.VoidReason,
	)
	return i, err
}

const listPointAdjustmentsForKid = `-- name: ListPointAdjustmentsForKid :many
SELECT id, kid_id, points_delta, reason, created_at, voided_at, void_reason FROM point_adjustments
WHERE kid_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListPointAdjustmentsForKidParams struct {
	KidID int64
	Limit int64
}

func (q *Queries) ListPointAdjustmentsForKid(ctx context.Context, arg ListPointAdjustmentsForKidParams) ([]PointAdjustment, error) {
	rows, err := q.db.QueryContext(ctx, listPointAdjustmentsForKid, arg.KidID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PointAdjustment{}
	for rows.Next() {
		var i PointAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.KidID,
			&i.PointsDelta,
			&i.Reason,
			&i.CreatedAt,
			&i.VoidedAt,
			&i.VoidReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumNegativePointAdjustmentsForKid = `-- name: SumNegativePointAdjustmentsForKid :one
SELECT CAST(COALESCE(-SUM(points_delta), 0) AS INTEGER) AS total
FROM point_adjustments
WHERE kid_id = ? AND voided_at IS NULL AND points_delta < 0
`

func (q *Queries) SumNegativePointAdjustmentsForKid(ctx context.Context, kidID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumNegativePointAdjustmentsForKid, kidID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumPointAdjustmentsForKid = `-- name: SumPointAdjustmentsForKid :one
SELECT CAST(COALESCE(SUM(points_delta), 0) AS INTEGER) AS total
FROM point_adjustments
WHERE kid_id = ? AND voided_at IS NULL
`

// Balance support: signed sum of non-voided adjustments for a kid.
// A positive total adds to Earned (when delta > 0) or to Spent (when delta < 0);
// the BalanceCalculator splits this in Go.
func (q *Queries) SumPointAdjustmentsForKid(ctx context.Context, kidID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumPointAdjustmentsForKid, kidID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumPositivePointAdjustmentsForKid = `-- name: SumPositivePointAdjustmentsForKid :one
SELECT CAST(COALESCE(SUM(points_delta), 0) AS INTEGER) AS total
FROM point_adjustments
WHERE kid_id = ? AND voided_at IS NULL AND points_delta > 0
`

// Balance support: separate positive (earned) and negative (spent) totals.
func (q *Queries) SumPositivePointAdjustmentsForKid(ctx context.Context, kidID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumPositivePointAdjustmentsForKid, kidID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const voidPointAdjustment = `-- name: VoidPointAdjustment :exec
UPDATE point_adjustments
SET voided_at = datetime('now'), void_reason = ?
WHERE id = ? AND voided_at IS NULL
`

type VoidPointAdjustmentParams struct {
	VoidReason *string
	ID         int64
}

func (q *Queries) VoidPointAdjustment(ctx context.Context, arg VoidPointAdjustmentParams) error {
	_, err := q.db.ExecContext(ctx, voidPointAdjustment, arg.VoidReason, arg.ID)
	return err
}
