// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: redemption.sql

package sqldb

import (
	"context"
	"time"
)

const getRedemption = `-- name: GetRedemption :one
SELECT id, kid_id, reward_id, points_spent, status, requested_at, decided_at FROM redemptions WHERE id = ?
`

func (q *Queries) GetRedemption(ctx context.Context, id int64) (Redemption, error) {
	row := q.db.QueryRowContext(ctx, getRedemption, id)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.KidID,
		&i.RewardID,
		&i.PointsSpent,
		&i.Status,
		&i.RequestedAt,
		&i.DecidedAt,
	)
	return i, err
}

const insertRedemption = `-- name: InsertRedemption :one
INSERT INTO redemptions (kid_id, reward_id, points_spent, status)
VALUES (?, ?, ?, 'pending')
RETURNING id, kid_id, reward_id, points_spent, status, requested_at, decided_at
`

type InsertRedemptionParams struct {
	KidID       int64
	RewardID    int64
	PointsSpent int64
}

func (q *Queries) InsertRedemption(ctx context.Context, arg InsertRedemptionParams) (Redemption, error) {
	row := q.db.QueryRowContext(ctx, insertRedemption, arg.KidID, arg.RewardID, arg.PointsSpent)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.KidID,
		&i.RewardID,
		&i.PointsSpent,
		&i.Status,
		&i.RequestedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listPendingRedemptions = `-- name: ListPendingRedemptions :many
SELECT r.id, r.kid_id, r.reward_id, r.points_spent, r.status, r.requested_at, r.decided_at, k.name AS kid_name, rw.name AS reward_name
FROM redemptions r
JOIN kids k ON k.id = r.kid_id
JOIN rewards rw ON rw.id = r.reward_id
WHERE r.status = 'pending'
ORDER BY r.requested_at
`

type ListPendingRedemptionsRow struct {
	ID          int64
	KidID       int64
	RewardID    int64
	PointsSpent int64
	Status      string
	RequestedAt time.Time
	DecidedAt   *time.Time
	KidName     string
	RewardName  string
}

func (q *Queries) ListPendingRedemptions(ctx context.Context) ([]ListPendingRedemptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingRedemptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingRedemptionsRow{}
	for rows.Next() {
		var i ListPendingRedemptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.KidID,
			&i.RewardID,
			&i.PointsSpent,
			&i.Status,
			&i.RequestedAt,
			&i.DecidedAt,
			&i.KidName,
			&i.RewardName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRedemptionsForKid = `-- name: ListPendingRedemptionsForKid :many
SELECT id, kid_id, reward_id, points_spent, status, requested_at, decided_at FROM redemptions
WHERE kid_id = ? AND status = 'pending'
ORDER BY requested_at
`

func (q *Queries) ListPendingRedemptionsForKid(ctx context.Context, kidID int64) ([]Redemption, error) {
	rows, err := q.db.QueryContext(ctx, listPendingRedemptionsForKid, kidID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Redemption{}
	for rows.Next() {
		var i Redemption
		if err := rows.Scan(
			&i.ID,
			&i.KidID,
			&i.RewardID,
			&i.PointsSpent,
			&i.Status,
			&i.RequestedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRedemptionsForKid = `-- name: ListRedemptionsForKid :many
SELECT id, kid_id, reward_id, points_spent, status, requested_at, decided_at FROM redemptions
WHERE kid_id = ?
ORDER BY requested_at DESC
LIMIT ?
`

type ListRedemptionsForKidParams struct {
	KidID int64
	Limit int64
}

func (q *Queries) ListRedemptionsForKid(ctx context.Context, arg ListRedemptionsForKidParams) ([]Redemption, error) {
	rows, err := q.db.QueryContext(ctx, listRedemptionsForKid, arg.KidID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Redemption{}
	for rows.Next() {
		var i Redemption
		if err := rows.Scan(
			&i.ID,
			&i.KidID,
			&i.RewardID,
			&i.PointsSpent,
			&i.Status,
			&i.RequestedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumApprovedRedemptionPointsForKid = `-- name: SumApprovedRedemptionPointsForKid :one
SELECT CAST(COALESCE(SUM(points_spent), 0) AS INTEGER) AS total
FROM redemptions
WHERE kid_id = ? AND status = 'approved'
`

// Balance support: sum approved redemption costs (the kid has "spent" these).
func (q *Queries) SumApprovedRedemptionPointsForKid(ctx context.Context, kidID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumApprovedRedemptionPointsForKid, kidID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumPendingRedemptionPointsForKid = `-- name: SumPendingRedemptionPointsForKid :one
SELECT CAST(COALESCE(SUM(points_spent), 0) AS INTEGER) AS total
FROM redemptions
WHERE kid_id = ? AND status = 'pending'
`

// Balance support: sum pending redemption costs (reserved against available balance).
func (q *Queries) SumPendingRedemptionPointsForKid(ctx context.Context, kidID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumPendingRedemptionPointsForKid, kidID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const transitionRedemptionStatus = `-- name: TransitionRedemptionStatus :exec
UPDATE redemptions
SET status = ?, decided_at = datetime('now')
WHERE id = ? AND status = ?
`

type TransitionRedemptionStatusParams struct {
	Status   string
	ID       int64
	Status_2 string
}

func (q *Queries) TransitionRedemptionStatus(ctx context.Context, arg TransitionRedemptionStatusParams) error {
	_, err := q.db.ExecContext(ctx, transitionRedemptionStatus, arg.Status, arg.ID, arg.Status_2)
	return err
}
