// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reward.sql

package sqldb

import (
	"context"
)

const archiveReward = `-- name: ArchiveReward :exec
UPDATE rewards SET archived_at = datetime('now') WHERE id = ? AND archived_at IS NULL
`

func (q *Queries) ArchiveReward(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, archiveReward, id)
	return err
}

const createReward = `-- name: CreateReward :one
INSERT INTO rewards (slug, name, description, cost_points, active)
VALUES (?, ?, ?, ?, ?)
RETURNING id, slug, name, description, cost_points, active, archived_at, created_at
`

type CreateRewardParams struct {
	Slug        string
	Name        string
	Description *string
	CostPoints  int64
	Active      int64
}

func (q *Queries) CreateReward(ctx context.Context, arg CreateRewardParams) (Reward, error) {
	row := q.db.QueryRowContext(ctx, createReward,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.CostPoints,
		arg.Active,
	)
	var i Reward
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CostPoints,
		&i.Active,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getReward = `-- name: GetReward :one
SELECT id, slug, name, description, cost_points, active, archived_at, created_at FROM rewards WHERE id = ?
`

func (q *Queries) GetReward(ctx context.Context, id int64) (Reward, error) {
	row := q.db.QueryRowContext(ctx, getReward, id)
	var i Reward
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CostPoints,
		&i.Active,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRewardBySlug = `-- name: GetRewardBySlug :one
SELECT id, slug, name, description, cost_points, active, archived_at, created_at FROM rewards WHERE slug = ? AND archived_at IS NULL
`

func (q *Queries) GetRewardBySlug(ctx context.Context, slug string) (Reward, error) {
	row := q.db.QueryRowContext(ctx, getRewardBySlug, slug)
	var i Reward
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CostPoints,
		&i.Active,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveRewards = `-- name: ListActiveRewards :many
SELECT id, slug, name, description, cost_points, active, archived_at, created_at FROM rewards
WHERE archived_at IS NULL AND active = 1
ORDER BY cost_points
`

func (q *Queries) ListActiveRewards(ctx context.Context) ([]Reward, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRewards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reward{}
	for rows.Next() {
		var i Reward
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CostPoints,
			&i.Active,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRewards = `-- name: ListRewards :many
SELECT id, slug, name, description, cost_points, active, archived_at, created_at FROM rewards WHERE archived_at IS NULL ORDER BY cost_points
`

func (q *Queries) ListRewards(ctx context.Context) ([]Reward, error) {
	rows, err := q.db.QueryContext(ctx, listRewards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reward{}
	for rows.Next() {
		var i Reward
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CostPoints,
			&i.Active,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveReward = `-- name: UnarchiveReward :exec
UPDATE rewards SET archived_at = NULL WHERE id = ?
`

func (q *Queries) UnarchiveReward(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unarchiveReward, id)
	return err
}

const updateReward = `-- name: UpdateReward :exec
UPDATE rewards
SET name = ?, description = ?, cost_points = ?, active = ?
WHERE id = ?
`

type UpdateRewardParams struct {
	Name        string
	Description *string
	CostPoints  int64
	Active      int64
	ID          int64
}

func (q *Queries) UpdateReward(ctx context.Context, arg UpdateRewardParams) error {
	_, err := q.db.ExecContext(ctx, updateReward,
		arg.Name,
		arg.Description,
		arg.CostPoints,
		arg.Active,
		arg.ID,
	)
	return err
}
